# Base configuration
base_url: https://my-rss-files.netlify.app  # Change this to your web provider URL

# Site configurations
sites:


  - id: trt test test3 test4
    url: https://www.trthaber.com/son-dakika-haberleri
    selector: .last-news-container .title a 

  - id: webb
    url: https://www.webtekno.com/haber
    selector: .content-timeline__detail__container > a

  - id: rp
    url: https://www.rp.pl/wydarzenia/kraj
    selector: .pt-6 a.md\:line-clamp-2

  - id: sabah
    url: https://www.sabah.com.tr/son-dakika-haberleri
    selector: .heading

  - id: polskie
    url: https://www.polskieradio.pl/395/7785
    selector: .title.title--big

  - id: defenceministry
    url: https://www.gov.pl/web/national-defence/news
    selector: .title

  - id: pap
    url: https://www.pap.pl/kraj?page=0
    selector: .title > a




