[build]
  publish = "."
  command = "pip install -r requirements.txt && python main.py"

[build.environment]
  PYTHON_VERSION = "3.8"

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/rss+xml"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"